import type { CompanyTemplateAgentDefinition, CompanyTemplateArtifactContract, CompanyTemplateDefinition, CompanyTemplateProjectDefinition } from "@paperclipai/shared";
import { READERSBASE_COMPANY_PACK_DOCUMENTS } from "./readersbase-company-pack.js";
import { READERSBASE_CREATIVE_SYSTEM_NOTE, READERSBASE_CURRENT_FICTION_PRIORITY_NOTE, READERSBASE_FICTION_DEPARTMENT_NOTE } from "./readersbase-notes.js";

export const READERSBASE_PUBLISHING_FORMATS = [
  "novel",
  "novella",
  "short-story",
  "interactive-novel",
  "interactive-novella",
  "interactive-short-story",
  "storybook",
  "graphic-novel",
] as const;

const defaultAdapterConfig = {
  model: "gpt-5.3-codex",
  modelReasoningEffort: "xhigh",
  promptTemplate: READERSBASE_CREATIVE_SYSTEM_NOTE,
};

const defaultRuntimeConfig = {
  heartbeat: {
    enabled: false,
    wakeOnDemand: true,
  },
};

function agent(
  slug: string,
  name: string,
  role: string,
  title: string,
  reportsToSlug: string | undefined,
  capabilities: string,
  departmentSlug: string,
  extraMetadata: Record<string, unknown> = {},
): CompanyTemplateAgentDefinition {
  return {
    slug,
    name,
    role,
    title,
    reportsToSlug,
    capabilities,
    adapterType: "codex_local",
    adapterConfig: defaultAdapterConfig,
    runtimeConfig: defaultRuntimeConfig,
    metadata: {
      templateSlug: "readersbase-publishing",
      departmentSlug,
      readersBaseBridgeRole: departmentSlug === "readersbase-bridge" ? "bridge" : undefined,
      ...extraMetadata,
    },
  };
}

const agents: CompanyTemplateAgentDefinition[] = [
  agent(
    "publisher-in-chief",
    "Publisher-in-Chief",
    "publisher_in_chief",
    "CEO / Publisher-in-Chief",
    undefined,
    "Sets publishing strategy, owns final quality posture, and approves governed ReadersBase publishing/export decisions.",
    "executive",
  ),
  agent("head-of-production", "Head of Production", "head_of_production", "COO / Production Manager", "publisher-in-chief", "Owns production planning, schedules, budgets, dependencies, and cross-phase handoff hygiene.", "production"),
  agent("production-planner", "Production Planner", "production_planner", "Production Planner", "head-of-production", "Turns approved publishing goals into phase plans, staffing, and issue sequencing.", "production"),
  agent("schedule-budget-controller", "Schedule & Budget Controller", "schedule_budget_controller", "Schedule & Budget Controller", "head-of-production", "Tracks campaign deadlines, model spend, blocked phases, and budget hard-stop risks.", "production"),
  agent("head-of-research", "Head of Research", "head_of_research", "Research Director", "publisher-in-chief", `Owns research strategy, evidence quality, and classification handoff. ${READERSBASE_FICTION_DEPARTMENT_NOTE}`, "research"),
  agent("market-audience-researcher", "Market & Audience Researcher", "market_audience_researcher", "Market & Audience Researcher", "head-of-research", "Studies reader expectations, comparable works, audience promises, and market positioning.", "research"),
  agent("setting-domain-researcher", "Setting & Domain Researcher", "setting_domain_researcher", "Setting & Domain Researcher", "head-of-research", "Collects setting, domain, historical, scientific, cultural, and source-truth evidence for story design.", "research"),
  agent("comparative-works-analyst", "Comparative Works Analyst", "comparative_works_analyst", "Comparative Works Analyst", "head-of-research", "Analyzes comps, shelf fit, reader promise, and differentiation for a proposed work.", "research"),
  agent("research-classification-agent", "Research & Classification Agent", "research_classification", "Research & Classification Agent", "head-of-research", `Classifies ReadersBase story work against source evidence, genres, formats, and canon handoffs. ${READERSBASE_FICTION_DEPARTMENT_NOTE}`, "research"),
  agent("head-of-story-architecture", "Head of Story Architecture", "head_of_story_architecture", "Chief Story Officer", "publisher-in-chief", "Owns premise, structure, character, continuity, world logic, and deep fiction quality before drafting scales.", "story-architecture"),
  agent("premise-architect", "Premise Architect", "premise_architect", "Premise Architect", "head-of-story-architecture", "Shapes premise, conflict engine, reader promise, and thematic spine.", "story-architecture"),
  agent("plot-structure-architect", "Plot & Structure Architect", "plot_structure_architect", "Plot & Structure Architect", "head-of-story-architecture", "Builds plot architecture, act structure, causality, reveals, and series/book arcs.", "story-architecture"),
  agent("character-architect", "Character Architect", "character_architect", "Character Architect", "head-of-story-architecture", "Owns protagonist, antagonist, cast arcs, motivation, relationships, and emotional continuity.", "story-architecture"),
  agent("continuity-keeper", "Continuity Keeper", "continuity_keeper", "Continuity Keeper", "head-of-story-architecture", "Maintains canon, timeline, lore, unresolved promises, and contradiction checks across artifacts.", "story-architecture"),
  agent("head-of-genre", "Head of Genre", "head_of_genre", "Genre Director", "publisher-in-chief", "Owns genre promise, subgenre fit, trope strategy, shelf expectations, and genre-specific quality gates.", "genre"),
  agent("genre-taxonomy-liaison", "Genre Taxonomy Liaison", "genre_taxonomy_liaison", "Genre Taxonomy Liaison", "head-of-genre", "Maintains bridge metadata to ReadersBase genre keys without duplicating the live taxonomy.", "genre", { readersBaseBridgeRole: "taxonomy-reference" }),
  agent("tropes-promise-analyst", "Tropes & Promise Analyst", "tropes_promise_analyst", "Tropes & Promise Analyst", "head-of-genre", "Checks trope compatibility, reader promise delivery, genre-mix risks, and shelf-positioning evidence.", "genre"),
  agent("subgenre-fit-reviewer", "Subgenre Fit Reviewer", "subgenre_fit_reviewer", "Subgenre Fit Reviewer", "head-of-genre", "Reviews subgenre selection, edge cases, exclusions, and bridge metadata before publication.", "genre"),
  agent("head-of-format", "Head of Format", "head_of_format", "Format Director", "publisher-in-chief", "Owns format-specific structure and quality for novels, novellas, short stories, interactive novels, storybooks, and graphic novels.", "format", { supportedFormats: READERSBASE_PUBLISHING_FORMATS }),
  agent("novel-novella-format-editor", "Novel & Novella Format Editor", "novel_novella_format_editor", "Novel & Novella Format Editor", "head-of-format", "Checks long-form manuscript expectations, pacing, chapter architecture, and novella/novel fit.", "format"),
  agent("short-serial-format-editor", "Short & Serial Format Editor", "short_serial_format_editor", "Short & Serial Format Editor", "head-of-format", "Checks short story, serial installment, anthology contribution, and serialization constraints.", "format"),
  agent("interactive-story-designer", "Interactive Story Designer", "interactive_story_designer", "Interactive Story Designer", "head-of-format", "Owns branching narrative structure, choice state, consequence maps, and interactive-reader affordances.", "format"),
  agent("storybook-designer", "Storybook Designer", "storybook_designer", "Storybook Designer", "head-of-format", "Owns storybook pacing, page turns, text-image handoffs, and accessibility for illustrated narratives.", "format"),
  agent("graphic-visual-narrative-designer", "Graphic & Visual Narrative Designer", "graphic_visual_narrative_designer", "Graphic & Visual Narrative Designer", "head-of-format", "Owns panel/page logic, visual continuity, script-to-art handoffs, and graphic narrative packaging.", "format"),
  agent("head-of-drafting", "Head of Drafting", "head_of_drafting", "Drafting Lead", "publisher-in-chief", "Owns manuscript drafting, prose execution, scene quality, and revision integration from approved design artifacts.", "drafting"),
  agent("scene-drafter", "Scene Drafter", "scene_drafter", "Scene Drafter", "head-of-drafting", "Drafts scenes from approved beats with conflict, setting, character intent, and continuity constraints.", "drafting"),
  agent("dialogue-specialist", "Dialogue Specialist", "dialogue_specialist", "Dialogue Specialist", "head-of-drafting", "Improves dialogue voice, subtext, conflict, exposition load, and character-specific speech patterns.", "drafting"),
  agent("prose-stylist", "Prose Stylist", "prose_stylist", "Prose Stylist", "head-of-drafting", "Raises prose quality, rhythm, imagery, clarity, and genre-appropriate style without breaking canon.", "drafting"),
  agent("revision-integrator", "Revision Integrator", "revision_integrator", "Revision Integrator", "head-of-drafting", "Integrates editorial, continuity, genre, and QA changes into coherent manuscript revisions.", "drafting"),
  agent("head-of-editorial", "Head of Editorial", "head_of_editorial", "Editorial Lead", "publisher-in-chief", "Owns developmental, line, copy, sensitivity, and risk reviews before publication packaging.", "editorial"),
  agent("developmental-editor", "Developmental Editor", "developmental_editor", "Developmental Editor", "head-of-editorial", "Reviews structure, pacing, arcs, stakes, theme, and reader promise at manuscript level.", "editorial"),
  agent("line-editor", "Line Editor", "line_editor", "Line Editor", "head-of-editorial", "Improves sentence-level clarity, voice, flow, and scene-by-scene readability.", "editorial"),
  agent("copy-editor", "Copy Editor", "copy_editor", "Copy Editor", "head-of-editorial", "Checks grammar, style consistency, facts, capitalization, punctuation, and house-style alignment.", "editorial"),
  agent("sensitivity-risk-reviewer", "Sensitivity & Risk Reviewer", "sensitivity_risk_reviewer", "Sensitivity & Risk Reviewer", "head-of-editorial", "Reviews sensitive content, rights risk, age fit, harmful stereotypes, and publication risk notes.", "editorial"),
  agent("head-of-publishing", "Head of Publishing", "head_of_publishing", "Publishing Lead", "publisher-in-chief", "Owns metadata, packaging, export readiness, launch copy, distribution handoffs, and board approval gate compliance.", "publishing"),
  agent("metadata-catalog-editor", "Metadata & Catalog Editor", "metadata_catalog_editor", "Metadata & Catalog Editor", "head-of-publishing", "Prepares title metadata, descriptions, categories, bridge manifests, and catalog-ready summaries.", "publishing", { readersBaseBridgeRole: "catalog-metadata" }),
  agent("export-packaging-specialist", "Export Packaging Specialist", "export_packaging_specialist", "Export Packaging Specialist", "head-of-publishing", "Packages manuscript, manifests, images, and external links for approved downstream publication.", "publishing"),
  agent("launch-copywriter", "Launch Copywriter", "launch_copywriter", "Launch Copywriter", "head-of-publishing", "Writes launch copy, blurbs, positioning, reader-facing summaries, and promotional snippets.", "publishing"),
  agent("distribution-coordinator", "Distribution Coordinator", "distribution_coordinator", "Distribution Coordinator", "head-of-publishing", "Coordinates publishing channels, release readiness, handoffs, and post-approval distribution checklist.", "publishing"),
  agent("head-of-qa-artifact-library", "Head of QA & Artifact Library", "head_of_qa_artifact_library", "QA / Artifact Librarian Lead", "publisher-in-chief", "Owns final acceptance, artifact completeness, handoff traceability, work-product metadata, and bridge QA.", "qa-artifact-library"),
  agent("continuity-qa-analyst", "Continuity QA Analyst", "continuity_qa_analyst", "Continuity QA Analyst", "head-of-qa-artifact-library", "Runs continuity, timeline, canon, character, setting, and unresolved-promise checks.", "qa-artifact-library"),
  agent("artifact-librarian", "Artifact Librarian", "artifact_librarian", "Artifact Librarian", "head-of-qa-artifact-library", "Ensures required artifacts exist, are keyed correctly, link to phases/issues, and carry review status metadata.", "qa-artifact-library"),
  agent("readersbase-bridge-qa", "ReadersBase Bridge QA", "readersbase_bridge_qa", "ReadersBase Bridge QA", "head-of-qa-artifact-library", "Validates bridge manifests, taxonomy references, catalog handoff assumptions, and no-live-mutation safety.", "qa-artifact-library", { readersBaseBridgeRole: "bridge-qa" }),
  agent("final-acceptance-reviewer", "Final Acceptance Reviewer", "final_acceptance_reviewer", "Final Acceptance Reviewer", "head-of-qa-artifact-library", "Runs the final acceptance gate across artifact completeness, quality gates, approvals, and publication readiness.", "qa-artifact-library"),
];

const projects: CompanyTemplateProjectDefinition[] = [
  ["production", "Production", "Campaign planning, schedules, budgets, and cross-phase control."],
  ["research", "Research", "Market, audience, source-truth, and setting/domain evidence."],
  ["story-architecture", "Story Architecture", "Premise, plot, character, continuity, and story bible work."],
  ["genre", "Genre", "Genre taxonomy references, trope strategy, and reader promise gates."],
  ["format", "Format", "Format-specific design for every supported publishing format."],
  ["drafting", "Drafting", "Manuscript drafting, prose, dialogue, and revisions."],
  ["editorial", "Editorial", "Developmental, line, copy, sensitivity, and risk review."],
  ["publishing", "Publishing", "Metadata, packaging, launch copy, and distribution handoff."],
  ["qa-artifact-library", "QA & Artifact Library", "QA gates, artifact tracking, final acceptance, and handoff library."],
  ["readersbase-bridge", "ReadersBase Bridge", "Bridge metadata and future ReadersBase integration boundary."],
].map(([slug, name, description]) => ({
  slug,
  name,
  description,
  goalSlug: "company-mission",
  metadata: {
    templateSlug: "readersbase-publishing",
    departmentSlug: slug,
    artifactPolicy: "required-phase-artifacts-use-documents-and-issue-work-products",
    readersBaseBridgeRole: slug === "readersbase-bridge" ? "bridge-metadata-only" : undefined,
  },
}));

const artifactContracts: CompanyTemplateArtifactContract[] = [
  {
    key: "research-brief",
    title: "Research Brief",
    phaseSlug: "research",
    projectSlug: "research",
    ownerAgentSlug: "head-of-research",
    kind: "markdown_document",
    lifecycle: "review_ready",
    reviewGates: ["lead_review"],
    required: true,
    metadata: { downstreamConsumer: "head-of-story-architecture" },
  },
  {
    key: "classification-bridge-manifest",
    title: "Classification Bridge Manifest",
    phaseSlug: "analysis",
    projectSlug: "genre",
    ownerAgentSlug: "genre-taxonomy-liaison",
    kind: "json_manifest",
    lifecycle: "review_ready",
    reviewGates: ["lead_review", "bridge_validation"],
    required: true,
    metadata: { readersBase: { taxonomyValidation: "future-bridge" } },
  },
  {
    key: "genre-reader-promise-gate",
    title: "Genre Reader Promise Gate",
    phaseSlug: "analysis",
    projectSlug: "genre",
    ownerAgentSlug: "head-of-genre",
    kind: "checklist",
    lifecycle: "approved",
    reviewGates: ["lead_review", "ceo_review"],
    required: true,
    metadata: { gateType: "genre-specific" },
  },
  {
    key: "story-bible",
    title: "Story Bible",
    phaseSlug: "story-design",
    projectSlug: "story-architecture",
    ownerAgentSlug: "head-of-story-architecture",
    kind: "bible",
    lifecycle: "approved",
    reviewGates: ["lead_review", "ceo_review"],
    required: true,
    metadata: { includes: ["premise", "plot", "characters", "world", "continuity"] },
  },
  {
    key: "format-design-spec",
    title: "Format Design Spec",
    phaseSlug: "story-design",
    projectSlug: "format",
    ownerAgentSlug: "head-of-format",
    kind: "outline",
    lifecycle: "approved",
    reviewGates: ["lead_review"],
    required: true,
    metadata: { supportedFormats: READERSBASE_PUBLISHING_FORMATS },
  },
  {
    key: "draft-manuscript",
    title: "Draft Manuscript",
    phaseSlug: "draft",
    projectSlug: "drafting",
    ownerAgentSlug: "head-of-drafting",
    kind: "manuscript",
    lifecycle: "review_ready",
    reviewGates: ["lead_review"],
    required: true,
    metadata: { downstreamConsumer: "head-of-editorial" },
  },
  {
    key: "deep-fiction-quality-gate",
    title: "Deep Fiction Quality Gate",
    phaseSlug: "draft",
    projectSlug: "story-architecture",
    ownerAgentSlug: "continuity-qa-analyst",
    kind: "qa_report",
    lifecycle: "approved",
    reviewGates: ["lead_review", "ceo_review", "final_acceptance"],
    required: true,
    metadata: { gateType: "deep-fiction", checks: ["plot", "character", "conflict", "setting", "continuity", "pacing"] },
  },
  {
    key: "editorial-review-report",
    title: "Editorial Review Report",
    phaseSlug: "editorial",
    projectSlug: "editorial",
    ownerAgentSlug: "head-of-editorial",
    kind: "qa_report",
    lifecycle: "approved",
    reviewGates: ["lead_review", "final_acceptance"],
    required: true,
    metadata: { includes: ["developmental", "line", "copy", "sensitivity-risk"] },
  },
  {
    key: "publishing-package",
    title: "Publishing Package",
    phaseSlug: "publishing",
    projectSlug: "publishing",
    ownerAgentSlug: "export-packaging-specialist",
    kind: "package",
    lifecycle: "review_ready",
    reviewGates: ["lead_review", "bridge_validation", "board_approval"],
    required: true,
    metadata: { noExternalPublicationWithoutBoardApproval: true },
  },
  {
    key: "publishing-approval-manifest",
    title: "Publishing Approval Manifest",
    phaseSlug: "publishing",
    projectSlug: "qa-artifact-library",
    ownerAgentSlug: "final-acceptance-reviewer",
    kind: "json_manifest",
    lifecycle: "approved",
    reviewGates: ["ceo_review", "board_approval", "final_acceptance"],
    required: true,
    metadata: { hardGate: true, downstreamConsumer: "readersbase-bridge-qa" },
  },
];

export const READERSBASE_PUBLISHING_TEMPLATE: CompanyTemplateDefinition = {
  schemaVersion: 1,
  slug: "readersbase-publishing",
  version: "1.0.0",
  name: "ReadersBase Publishing",
  description: "Reusable Paperclip company template for a governed ReadersBase-native fiction publishing house.",
  company: {
    name: "ReadersBase Publishing",
    issuePrefix: "RB",
    description: "AI publishing company for ReadersBase-native fiction and narrative content.",
    requireBoardApprovalForNewAgents: true,
    metadata: {
      templateSlug: "readersbase-publishing",
      templateVersion: "1.0.0",
      domain: "readersbase-publishing",
      bridge: "readersbase",
    },
  },
  agents,
  goals: [
    {
      slug: "company-mission",
      title: "Publish ReadersBase-native fiction with governed quality gates",
      description: "Create high-quality narrative works through research, analysis, story design, draft, editorial, and publishing phases while preserving board approval for external publication.",
      level: "company",
      ownerAgentSlug: "publisher-in-chief",
      metadata: { templateSlug: "readersbase-publishing" },
    },
  ],
  projects,
  campaignTemplates: [
    {
      slug: "fiction-production",
      title: "Fiction Production Campaign",
      objective: "Move a fiction concept through research, analysis, story design, draft, editorial, and publishing gates.",
      leadAgentSlug: "head-of-production",
      projectSlugs: projects.map((project) => project.slug),
      phases: [
        { slug: "research", title: "Research", sequence: 1, objective: "Collect market, audience, setting, domain, and source-truth evidence before story decisions.", ownerAgentSlug: "head-of-research", projectSlug: "research", requiredArtifactKeys: ["research-brief"], planTemplate: `# Research phase plan\n\n${READERSBASE_FICTION_DEPARTMENT_NOTE}\n` },
        { slug: "analysis", title: "Analysis", sequence: 2, objective: "Classify format, genre, subgenre, reader promise, and bridge metadata without mutating ReadersBase.", ownerAgentSlug: "head-of-genre", projectSlug: "genre", requiredArtifactKeys: ["classification-bridge-manifest", "genre-reader-promise-gate"] },
        { slug: "story-design", title: "Story Design", sequence: 3, objective: "Approve premise, format design, story bible, continuity model, and quality-gate checklist before drafting.", ownerAgentSlug: "head-of-story-architecture", projectSlug: "story-architecture", requiredArtifactKeys: ["story-bible", "format-design-spec"] },
        { slug: "draft", title: "Draft", sequence: 4, objective: "Create manuscript or narrative package from approved story-design artifacts and pass deep fiction QA.", ownerAgentSlug: "head-of-drafting", projectSlug: "drafting", requiredArtifactKeys: ["draft-manuscript", "deep-fiction-quality-gate"] },
        { slug: "editorial", title: "Editorial", sequence: 5, objective: "Complete developmental, line, copy, sensitivity, and risk review with traceable revisions.", ownerAgentSlug: "head-of-editorial", projectSlug: "editorial", requiredArtifactKeys: ["editorial-review-report"] },
        { slug: "publishing", title: "Publishing", sequence: 6, objective: "Prepare metadata, export package, bridge manifest, launch copy, and board-approved publication handoff.", ownerAgentSlug: "head-of-publishing", projectSlug: "publishing", requiredArtifactKeys: ["publishing-package", "publishing-approval-manifest"] },
      ],
      metadata: { templateSlug: "readersbase-publishing" },
    },
  ],
  artifactContracts,
  documents: READERSBASE_COMPANY_PACK_DOCUMENTS,
  metadata: {
    templateSlug: "readersbase-publishing",
    priorityRouting: {
      primaryFormats: ["novel", "interactive-novel", "graphic-novel"],
      priorityGenres: ["fantasy", "science_fantasy", "sci-fi"],
      pausedByDefault: ["standalone-short-story", "standalone-novella"],
      requiresBoardApprovalBeforeExternalPublication: true,
      note: READERSBASE_CURRENT_FICTION_PRIORITY_NOTE,
    },
    bridgeBoundary: "metadata-only; live ReadersBase taxonomy/catalog mutation is deferred to a future bridge adapter",
  },
};
